### ISSUE TITLE
Generating Impossible Passwords.

### ISSUE THREAD

**Issue by RinnosukeM** [alexras/truepeacein.space#2]
Since it's another problem all together, I'll submit it as a different one.

While it's not possible to generate impossible passwords when you start at the 000000 000000 default password, it still is possible to generate them when you type custom passwords.

The 5 non-beam special items have two bits in the code. 1 to tell the game if they should be on the map or not, and one to tell if Samus has the ability/item. The continue screen doesn't deny a password if those two bits doesn't match.
_Just like it accepts password where the missiles count is above the maximum or where the Wave and Ice beam are enabled at the same time, even if both are impossible in the main game._

For the case of passwords with those two bits not matching, all found by either sheer luck or by machine, you could get an item twice in a run, or won't be able to get it at all.

It's possible to get through the game normally without most of the items, but there's one exception to the rule : The Morph Ball (Or Maru Mari.)
**Any password in the branch of 0G0000 000000 000000 000001 _(But not 0G0000 000000 400000 00000H)_ are thus impossible to complete.**

**A way to fix it, or at least to have the user be warned about it,** would be to make a second row where you can decide if an item is gone or not.
In the order of the site, here's the bits that give the info for those item.
(^Morph Ball, Bombs, High Jump, Varia, Screw Attack.)
Bits for having the power : 76, 72, 73, 77, 75,
Bits for taking away the items from the map : 0, 6, 24, 11, 26,

**Comment by alexras** [comment]
Thanks for filing both this and #1. Hopefully I can take a look at these and get them resolved in the next week or so.
